# Build worker image (VM template)
image:
- ubuntu1804
- Visual Studio 2017

init:
- cmd: set OPENMAMA_INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\install
- cmd: set GENERATOR="Visual Studio 15 2017 Win64"
- cmd: set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
- sh: export OPENMAMA_INSTALL_DIR=$APPVEYOR_BUILD_FOLDER/install
- sh: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# scripts that run after cloning repository
install:
- cmd: choco install -y unzip gow wget gradle nunit-console-runner nunit-extension-nunit-v2-driver
- cmd: refreshenv
- cmd: set PATH=C:\ProgramData\chocolatey\bin;%PATH%
- sh: sudo apt-get update -qq
- sh: sudo apt-get install -y scons git flex uuid-dev libevent-dev cmake git libzmq3-dev openjdk-8-jdk ncurses-dev ant unzip valgrind libapr1-dev

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# scripts to run before build
before_build:
- cmd: |-
    mkdir %APPVEYOR_BUILD_FOLDER%\qpid-proton
    cd %APPVEYOR_BUILD_FOLDER%\qpid-proton
    wget "https://github.com/apache/qpid-proton/archive/0.15.0.zip"
    unzip 0.15.0.zip
    cd qpid-proton-0.15.0
    mkdir bld
    cd bld
    cmake -DBUILD_TESTING=OFF -DBUILD_JAVA=OFF -DBUILD_CPP=OFF .. -G %GENERATOR%
    cmake --build . --config Release --target install
- cmd: |-
    mkdir %APPVEYOR_BUILD_FOLDER%\googletest
    cd %APPVEYOR_BUILD_FOLDER%\googletest
    wget "https://github.com/google/googletest/archive/release-1.8.0.zip"
    unzip release-1.8.0.zip
    cd googletest-release-1.8.0
    mkdir bld
    cd bld
    cmake -DCMAKE_CXX_FLAGS=-D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING -DBUILD_SHARED_LIBS=ON -DBUILD_GTEST=ON -DBUILD_GMOCK=OFF -G %GENERATOR% ..
    cmake --build . --config Release --target install
- cmd: |-
    mkdir %APPVEYOR_BUILD_FOLDER%\..\libevent
    cd %APPVEYOR_BUILD_FOLDER%\..\libevent
    wget "https://github.com/libevent/libevent/archive/release-2.1.8-stable.tar.gz"
    cmake -E tar xzf release-2.1.8-stable.tar.gz
    cd libevent-release-2.1.8-stable
    mkdir bld
    cd bld
    cmake -DEVENT__DISABLE_OPENSSL=ON -G %GENERATOR% ..
    type include\event2\event-config.h
    cmake --build . --config Release --target install
- cmd: |-
    mkdir %APPVEYOR_BUILD_FOLDER%\apr
    cd %APPVEYOR_BUILD_FOLDER%\apr
    wget "https://github.com/apache/apr/archive/1.6.3.zip"
    unzip 1.6.3.zip
    dir
    cd apr-1.6.3
    mkdir bld
    cd bld
    cmake -G %GENERATOR% ..
    cmake --build . --config Release --target install
- sh: |-
    mkdir $APPVEYOR_BUILD_FOLDER/googletest
    cd $APPVEYOR_BUILD_FOLDER/googletest
    wget "https://github.com/google/googletest/archive/release-1.8.0.zip"
    unzip release-1.8.0.zip
    cd googletest-release-1.8.0
    mkdir bld
    cd bld
    cmake -DBUILD_TESTING:BOOL=OFF -DBUILD_JAVA:BOOL=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
    sudo cmake --build . --config Release --target install
- sh: |-
    mkdir $APPVEYOR_BUILD_FOLDER\qpid-proton
    cd $APPVEYOR_BUILD_FOLDER\qpid-proton
    wget "https://github.com/apache/qpid-proton/archive/0.24.0.zip"
    unzip 0.24.0.zip
    cd qpid-proton-0.24.0
    mkdir bld
    cd bld
    cmake -DBUILD_TESTING:BOOL=OFF -DBUILD_CPP:BOOL=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
    sudo cmake --build . --config Release --target install

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: |-
      cd %APPVEYOR_BUILD_FOLDER%
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_CSHARP=ON -DWITH_UNITTEST=ON -DWITH_JAVA=ON -DINSTALL_RUNTIME_DEPENDENCIES=ON -DCMAKE_INSTALL_PREFIX=%OPENMAMA_INSTALL_DIR% -G %GENERATOR% ..
      cmake --build . --config RelWithDebInfo --target install
      cd ..
      python release_scripts\ci-run.py
  - sh: |-
      cd $APPVEYOR_BUILD_FOLDER
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_UNITTEST=ON -DWITH_JAVA=ON -DINSTALL_RUNTIME_DEPENDENCIES=ON -DCMAKE_INSTALL_PREFIX=$OPENMAMA_INSTALL_DIR -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_C_FLAGS=-Werror -DJAVA_HOME=$JAVA_HOME ..
      cmake --build . --config RelWithDebInfo --target install
      cd ..
      python release_scripts/ci-run.py

# The build script already tests as well and this one doesnt work for some reason anyway
test: off
